/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core"
import * as __TAURI_EVENT from "@tauri-apps/api/event"

/** Commands */
export const commands = {
	rsGetFrameworkVersion: () => __TAURI_INVOKE<string>("rs_get_framework_version"),
	rsGetLatestSmfVersion: () => __TAURI_INVOKE<string>("rs_get_latest_smf_version"),
	rsGetSmfChangelog: () => __TAURI_INVOKE<string>("rs_get_smf_changelog"),
	rsGetNexusVersion: (game: string, id: number) => __TAURI_INVOKE<string>("rs_get_nexus_version", { game, id }),
	rsGetGithubVersion: (repository: string) => __TAURI_INVOKE<string>("rs_get_github_version", { repository }),
	rsGetGithubDownloadUrl: (repository: string) => __TAURI_INVOKE<string>("rs_get_github_download_url", { repository }),
	rsGetGithubChangelog: (currentVer: string, repository: string) => __TAURI_INVOKE<string>("rs_get_github_changelog", { currentVer, repository }),
	rsGetModworkshopVersion: (id: number) => __TAURI_INVOKE<string>("rs_get_modworkshop_version", { id }),
	rsGetModworkshopDownloadUrl: (id: number) => __TAURI_INVOKE<string>("rs_get_modworkshop_download_url", { id }),
	rsExtractArchive: (archive: string, output: string) => __TAURI_INVOKE<null>("rs_extract_archive", { archive, output }),
	rsUpdateFramework: () => __TAURI_INVOKE<null>("rs_update_framework"),
	rsResolveModRelativePath: (modId: string, path: string) => __TAURI_INVOKE<string>("rs_resolve_mod_relative_path", { modId, path }),
	rsEvaluateCondition: (attribution: string, condition: string, enabledModVersions: { [key in string]: string }, platform: string, config: Config) =>
		__TAURI_INVOKE<boolean>("rs_evaluate_condition", { attribution, condition, enabledModVersions, platform, config }),
	rsValidateModFolder: (folder: string, lenient: boolean) => __TAURI_INVOKE<ValidationResult>("rs_validate_mod_folder", { folder, lenient }),
	rsCopyFolder: (from: string, to: string) => __TAURI_INVOKE<null>("rs_copy_folder", { from, to }),
	rsGetManifestSchema: () =>
		__TAURI_INVOKE<
			| "Null"
			| ({ Bool: boolean } & { Array?: never; Number?: never; Object?: never; String?: never })
			| ({ Number: ({ f64: number } & { i64?: never; u64?: never }) | ({ i64: number } & { f64?: never; u64?: never }) | ({ u64: number } & { f64?: never; i64?: never }) } & {
					Array?: never
					Bool?: never
					Object?: never
					String?: never
			  })
			| ({ String: string } & { Array?: never; Bool?: never; Number?: never; Object?: never })
			| ({ Array: Value[] } & { Bool?: never; Number?: never; Object?: never; String?: never })
			| ({ Object: { [key in string]: Value } } & { Array?: never; Bool?: never; Number?: never; String?: never })
		>("rs_get_manifest_schema"),
	rsGetExperiment: () => __TAURI_INVOKE<string | null>("rs_get_experiment"),
	rsGetProxiedModVersion: (modUrl: string) => __TAURI_INVOKE<string>("rs_get_proxied_mod_version", { modUrl }),
	rsValidateNumberOption: (option: NumberOptionValidation_Deserialize, value: number) => __TAURI_INVOKE<ValidationResult>("rs_validate_number_option", { option, value }),
	rsExtractRpkg: (rpkgPath: string, toFolder: string) => __TAURI_INVOKE<null>("rs_extract_rpkg", { rpkgPath, toFolder }),
	rsSaveDebugProfile: () => __TAURI_INVOKE<null>("rs_save_debug_profile"),
	rsGetTonytoolsHashListVersion: () => __TAURI_INVOKE<number | null>("rs_get_tonytools_hash_list_version"),
	rsDetectGameInstalls: () => __TAURI_INVOKE<GameInstall[]>("rs_detect_game_installs"),
	rsDeploy: () => __TAURI_INVOKE<null>("rs_deploy"),
	rsUpgradeMod: (gamePath: string, modInfo: { [key in string]: ModInfo }, modFolder: string) => __TAURI_INVOKE<null>("rs_upgrade_mod", { gamePath, modInfo, modFolder }),
	rsGetLatestSdkRelease: (version: GlacierGame) => __TAURI_INVOKE<string>("rs_get_latest_sdk_release", { version }),
	rsGetLatestSdkDownloadUrl: (version: GlacierGame, artifact: boolean) => __TAURI_INVOKE<string>("rs_get_latest_sdk_download_url", { version, artifact }),
	rsGetInstalledSdkVersion: (retailPath: string) => __TAURI_INVOKE<string | null>("rs_get_installed_sdk_version", { retailPath }),
	rsDetectGame: (path: string) =>
		__TAURI_INVOKE<{
			version: GlacierGame
			platform: Platform
			// An MD5 hash of the game executable (or game config, if Microsoft).
			hash: string
			// The Retail folder.
			path: string
		} | null>("rs_detect_game", { path }),
	rsValidateStringOption: (option: StringOptionValidation_Deserialize, value: string) => __TAURI_INVOKE<ValidationResult>("rs_validate_string_option", { option, value }),
	rsCanonicalizePath: (path: string) => __TAURI_INVOKE<string>("rs_canonicalize_path", { path }),
	rsGetLatestSdkArtifact: (version: GlacierGame) => __TAURI_INVOKE<string>("rs_get_latest_sdk_artifact", { version })
}

/** Events */
export const events = {
	deployError: makeEvent<DeployError>("deploy-error"),
	deployExitCode: makeEvent<DeployExitCode>("deploy-exit-code"),
	deployIpcMessage: makeEvent<DeployIPCMessage>("deploy-ipc-message"),
	deployOutput: makeEvent<DeployOutput>("deploy-output"),
	modUpgradeProgress: makeEvent<ModUpgradeProgress>("mod-upgrade-progress")
}

/* Types */
// The SMF config.
export type Config = {
	gamePath: string | null
	skipIntro: boolean
	useAlternativeOutputDirectory: string | null
	deployOrder: string[]
	modOptions: { [key in string]: { [key in string]: ModOptionValue } }
	developerMode: boolean
	onlineServices: boolean
	autoDisableDynres: boolean
	profiles: { [key in string]: ModProfile }
	uiLocale: string
	bootScene: string | null
	// GUI state irrelevant to the deploy process.
	gui: {
		[key in string]:
			| "Null"
			| ({ Bool: boolean } & { Array?: never; Number?: never; Object?: never; String?: never })
			| ({ Number: ({ f64: number } & { i64?: never; u64?: never }) | ({ i64: number } & { f64?: never; u64?: never }) | ({ u64: number } & { f64?: never; i64?: never }) } & {
					Array?: never
					Bool?: never
					Object?: never
					String?: never
			  })
			| ({ String: string } & { Array?: never; Bool?: never; Number?: never; Object?: never })
			| ({ Array: Value[] } & { Bool?: never; Number?: never; Object?: never; String?: never })
			| ({ Object: { [key in string]: Value } } & { Array?: never; Bool?: never; Number?: never; String?: never })
	}
}

export type DeployError = string

export type DeployExitCode = number

export type DeployIPCMessage = DeployMessage

export type DeployMessage =
	| {
			type: "diagnostic"
			data: {
				data: DiagnosticKind
				target: DiagnosticTarget
				severity: DiagnosticSeverity
				message: string
			}
	  }
	| {
			type: "progressStart"
			data: {
				name: string
				max: number
				id: number
			}
	  }
	| {
			type: "spinnerStart"
			data: {
				prefix: string
				target: string | null
				name: string
				id: number
			}
	  }
	| {
			type: "progressAdvance"
			data: {
				id: number
				amount: number
			}
	  }
	| {
			type: "progressFinish"
			data: {
				id: number
			}
	  }
	| { type: "unrecognisedGameVersion" }

export type DeployOutput = string

// A summary of the deploy.
export type DeploySummary = {
	game: Game
	frameworkPath: string
	frameworkVersion: string
	config: Config
	modVersions: { [key in string]: string }
	serverSideData: ServerSideData
	totalTime: number
}

export type DiagnosticKind =
	| {
			type: "resourceAlreadyIdentical"
			data: {
				resource: ResourceSpecifier
			}
	  }
	| {
			type: "unsupportedPlatform"
			data: {
				platform: string
				supported: string[]
			}
	  }
	| {
			type: "applyingMigration"
			data: {
				message: string
			}
	  }
	| {
			type: "unrecognizedPatch"
			data: {
				file_name: string
			}
	  }
	| {
			type: "unrecognizedPartitionPatch"
			data: {
				file_name: string
			}
	  }
	| {
			type: "quickEntityPatchDiagnostic"
			data: {
				diagnostic: string
			}
	  }
	| { type: "quickEntityPatchNoEffect" }
	| {
			type: "destinationsItemNotFoundBefore"
			data: {
				identifier: string
			}
	  }
	| {
			type: "destinationsItemNotFoundAfter"
			data: {
				identifier: string
			}
	  }
	| {
			type: "localisationOverrideSameValue"
			data: {
				lang: string
				key: string
			}
	  }
	| {
			type: "scriptDebug"
			data: {
				message: string
			}
	  }
	| {
			type: "referencedResourceNonexistent"
			data: {
				resource_id: string
				reference_type: ReferenceType
			}
	  }
	| {
			type: "referencedResourceDeleted"
			data: {
				resource_id: string
				reference_type: ReferenceType
			}
	  }
	| {
			type: "packageDefinitionPlatformPath"
			data: {
				suffix: string
			}
	  }

export type DiagnosticSeverity = { type: "low" } | { type: "medium" } | { type: "high" }

export type DiagnosticTarget =
	| { type: "none" }
	| {
			type: "mod"
			data: {
				modId: string
			}
	  }
	| {
			type: "operation"
			data: {
				// The source of this node; the mod's ID.
				modId: string
				// The file which produced this node, relative to the mod root.
				source: string
				// If this node was produced by a script, a unique identifier for the operation distinguishing it from others from the same script.
				scriptIdentifier: string | null
			}
	  }

export type ExplainedCondition = {
	/**
	 *  A condition written in Rune. Should be formatted as an expression.
	 *  Some helper functions are given in the global scope.
	 *  The framework config and game (version and platform) are available in the global scope as `config` and `game`.
	 *  For example, `mod_option("Author.SomeMod@1.0.0", "an-option") == Some("a-value")`.
	 */
	condition: string
	/**
	 *  A short explanation of the condition, to be shown to the user when the condition is not met.
	 *  For example, "Incompatible with Lighting Ultimate's Vanilla+ Sapienza" or "Requires either Mod A or Mod B to be enabled".
	 *  Should not end with punctuation.
	 */
	explanation: UIText
}

// Information about a game being deployed to.
export type Game = {
	version: GlacierGame
	platform: Platform
	// An MD5 hash of the game executable (or game config, if Microsoft).
	hash: string
	// The Retail folder.
	path: string
}

export type GameInstall = {
	version: GlacierGame
	platform: StorePlatform
	path: string
}

export type GlacierGame = "h1" | "h2" | "h3" | "fl"

export type Links = Links_Serialize | Links_Deserialize

export type Links_Deserialize = {
	// A link to documentation about the mod, separate to its host/homepage (e.g. mod wiki).
	info: string | null
	// A link to report issues with the mod (e.g. Nexus comments section, GitHub Issues page).
	issues: string | null
	// A link to support the mod's development (e.g. Patreon, Ko-fi, GitHub Sponsors).
	support: string | null
}

export type Links_Serialize = {
	// A link to documentation about the mod, separate to its host/homepage (e.g. mod wiki).
	info?: string | null
	// A link to report issues with the mod (e.g. Nexus comments section, GitHub Issues page).
	issues?: string | null
	// A link to support the mod's development (e.g. Patreon, Ko-fi, GitHub Sponsors).
	support?: string | null
}

export type Localisation = Localisation_Serialize | Localisation_Deserialize

export type Localisation_Deserialize = {
	english: string | null
	french: string | null
	italian: string | null
	german: string | null
	spanish: string | null
	spanishMexico: string | null
	portugueseBrazil: string | null
	turkish: string | null
	polish: string | null
	russian: string | null
	chineseSimplified: string | null
	chineseTraditional: string | null
	japanese: string | null
	korean: string | null
}

export type Localisation_Serialize = {
	english?: string | null
	french?: string | null
	italian?: string | null
	german?: string | null
	spanish?: string | null
	spanishMexico?: string | null
	portugueseBrazil?: string | null
	turkish?: string | null
	polish?: string | null
	russian?: string | null
	chineseSimplified?: string | null
	chineseTraditional?: string | null
	japanese?: string | null
	korean?: string | null
}

// A mod manifest.
export type Manifest = Manifest_Serialize | Manifest_Deserialize

export type ManifestConditions = ManifestConditions_Serialize | ManifestConditions_Deserialize

export type ManifestConditions_Deserialize = {
	/**
	 *  Games that this mod supports. All other games will be considered unsupported by this mod.
	 *
	 *  You can specify entire game versions (e.g. h1) or specific version/platform combinations (e.g. h3-epic).
	 *
	 *  Use this when a mod uses features that only some games support, such as Ghost Mode and H2 (plus H3 Steam).
	 */
	supportedGames?: string[]
	/**
	 *  Mods that this mod depends on to function. Clients without these mods enabled will be prevented from using this mod.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	requiredMods?: ModReference[]
	// Conditions which this mod depends on to function. When any condition is not met, the user will be prevented from using this mod.
	requiredConditions?: ExplainedCondition[]
	/**
	 *  Mods that this mod will not function with. Clients with these mods enabled will be prevented from using this mod.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	incompatibleMods?: ModReference[]
	// Conditions which this mod is incompatible with. When any condition is met, the user will be prevented from using this mod.
	incompatibleConditions?: ExplainedCondition[]
}

export type ManifestConditions_Serialize = {
	/**
	 *  Games that this mod supports. All other games will be considered unsupported by this mod.
	 *
	 *  You can specify entire game versions (e.g. h1) or specific version/platform combinations (e.g. h3-epic).
	 *
	 *  Use this when a mod uses features that only some games support, such as Ghost Mode and H2 (plus H3 Steam).
	 */
	supportedGames?: string[]
	/**
	 *  Mods that this mod depends on to function. Clients without these mods enabled will be prevented from using this mod.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	requiredMods?: ModReference[]
	// Conditions which this mod depends on to function. When any condition is not met, the user will be prevented from using this mod.
	requiredConditions?: ExplainedCondition[]
	/**
	 *  Mods that this mod will not function with. Clients with these mods enabled will be prevented from using this mod.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	incompatibleMods?: ModReference[]
	// Conditions which this mod is incompatible with. When any condition is met, the user will be prevented from using this mod.
	incompatibleConditions?: ExplainedCondition[]
}

export type ManifestData = ManifestData_Serialize | ManifestData_Deserialize

export type ManifestData_Deserialize = {
	// Folders with content files that will be crawled and automatically deployed.
	contentFolders?: string[]
	// Folders with blobs that will be crawled and automatically deployed.
	blobFolders?: string[]
	// Localisation keys (and their text values) to make globally available.
	localisation?: { [key in string]: Localisation_Deserialize }
	// LINE files to create from localisation IDs.
	localisedLines?: { [key in string]: string }
	// Paths to add to packagedefinition. Custom partitions are not supported.
	packageDefinition?: PackageDefinitionEntity[]
	// Resources that will be made available to a given partition (or super/chunk0 if unspecified).
	portResources?: PortedResource[]
	/**
	 *  Mods that this mod should deploy before. Used in automatic sorting by the Mod Manager.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	deployBefore?: ModReference[]
	/**
	 *  Mods that this mod should deploy after. Used in automatic sorting by the Mod Manager.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	deployAfter?: ModReference[]
	// Paths to plugins that Peacock should load when this mod is deployed.
	peacockPlugins?: string[]
	// Game versions, and the paths to mod DLLs that the appropriate SDK (ZHMModSDK/ZKntSDK) should load when this mod is deployed.
	sdkMods?: Partial<{ [key in GlacierGame]: string[] }>
	// Paths to Rune files that can alter deployment of the mod. The scripting API is currently unstable and may change between framework versions.
	scripts?: string[]
}

export type ManifestData_Serialize = {
	// Folders with content files that will be crawled and automatically deployed.
	contentFolders?: string[]
	// Folders with blobs that will be crawled and automatically deployed.
	blobFolders?: string[]
	// Localisation keys (and their text values) to make globally available.
	localisation?: { [key in string]: Localisation_Serialize }
	// LINE files to create from localisation IDs.
	localisedLines?: { [key in string]: string }
	// Paths to add to packagedefinition. Custom partitions are not supported.
	packageDefinition?: PackageDefinitionEntity[]
	// Resources that will be made available to a given partition (or super/chunk0 if unspecified).
	portResources?: PortedResource[]
	/**
	 *  Mods that this mod should deploy before. Used in automatic sorting by the Mod Manager.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	deployBefore?: ModReference[]
	/**
	 *  Mods that this mod should deploy after. Used in automatic sorting by the Mod Manager.
	 *  Should be specified as `modID@version`, where version can be a simple version (e.g. `1.0.0`, meaning 1.x.x) or a range specifier in standard npm-style syntax (e.g. `^2.0.0` or `1.2.0-1.3.1`).
	 */
	deployAfter?: ModReference[]
	// Paths to plugins that Peacock should load when this mod is deployed.
	peacockPlugins?: string[]
	// Game versions, and the paths to mod DLLs that the appropriate SDK (ZHMModSDK/ZKntSDK) should load when this mod is deployed.
	sdkMods?: Partial<{ [key in GlacierGame]: string[] }>
	// Paths to Rune files that can alter deployment of the mod. The scripting API is currently unstable and may change between framework versions.
	scripts?: string[]
}

// A mod manifest.
export type Manifest_Deserialize = {
	// The mod's ID. Should follow capitalised reverse URI style (AuthorName.ModName). Don't include special characters; numbers are OK. Words should be separated by CamelCase.
	id: string
	// The name of the mod.
	name: UIText
	// A description of the mod.
	description: UIText
	// A list of the mod's authors.
	authors: string[]
	/**
	 *  The mod's version, using semantic versioning (X.Y.Z). As applied to mods:
	 *  - updates with only bug fixes/patches increment the third number (patch version)
	 *  - updates with any new features increment the second number (minor version)
	 *  - updates which change the mod's behaviour in relation to other mods increment the first number (major version)
	 *
	 *  The major version should almost never be changed if the mod has not massively changed, but any change which affects other mods (for example, in compatibility or incompatibility) MUST increment it.
	 *  For example, if the new version makes your mod newly compatible with another mod, the major version should be incremented so that any `incompatibilities` keys from other mods no longer affect yours.
	 */
	version: string
	// The earliest version of the framework that this specific version of the mod has been tested against.
	frameworkVersion: string
	/**
	 *  A link to the mod's primary host (must be HTTPS).
	 *  - A mod hosted on Nexus should link to the Nexus page (e.g. https://nexusmods.com/hitman3/mods/453 - you can find the link before releasing the mod by using the preview function).
	 *  - A mod hosted on GitHub should use the GitHub repository link (https://github.com/Notexe/Portable-Chair).
	 *  - ModWorkshop mods should use their link (https://modworkshop.net/mod/45444).
	 *
	 *  Each platform has differing support for SMF features.
	 *  - GitHub repositories and ModWorkshop mods support fully automatic updating.
	 *  - GitHub repositories additionally support proper changelogs for mods, so users can see all the differences (across all releases) between their version and the latest. ModWorkshop does not support changelogs.
	 *  - Nexus Mods only allows for telling the user when an update is available, so the other two platforms are preferable.
	 *
	 *  In short: use GitHub if you can, ModWorkshop if you really don't want to, and Nexus Mods as a last resort.
	 */
	url: UrlOrNull
	// Relevant links for the mod.
	links?: Links_Deserialize
	conditions?: ManifestConditions_Deserialize
	data?: ManifestData_Deserialize
	// Settings for the mod that can be customised in the Mod Manager.
	options?: ModOption_Deserialize[]
	// Preset combinations of mod options that can be selected all at once.
	presets?: OptionPreset_Deserialize[]
}

// A mod manifest.
export type Manifest_Serialize = {
	// The mod's ID. Should follow capitalised reverse URI style (AuthorName.ModName). Don't include special characters; numbers are OK. Words should be separated by CamelCase.
	id: string
	// The name of the mod.
	name: UIText
	// A description of the mod.
	description: UIText
	// A list of the mod's authors.
	authors: string[]
	/**
	 *  The mod's version, using semantic versioning (X.Y.Z). As applied to mods:
	 *  - updates with only bug fixes/patches increment the third number (patch version)
	 *  - updates with any new features increment the second number (minor version)
	 *  - updates which change the mod's behaviour in relation to other mods increment the first number (major version)
	 *
	 *  The major version should almost never be changed if the mod has not massively changed, but any change which affects other mods (for example, in compatibility or incompatibility) MUST increment it.
	 *  For example, if the new version makes your mod newly compatible with another mod, the major version should be incremented so that any `incompatibilities` keys from other mods no longer affect yours.
	 */
	version: string
	// The earliest version of the framework that this specific version of the mod has been tested against.
	frameworkVersion: string
	/**
	 *  A link to the mod's primary host (must be HTTPS).
	 *  - A mod hosted on Nexus should link to the Nexus page (e.g. https://nexusmods.com/hitman3/mods/453 - you can find the link before releasing the mod by using the preview function).
	 *  - A mod hosted on GitHub should use the GitHub repository link (https://github.com/Notexe/Portable-Chair).
	 *  - ModWorkshop mods should use their link (https://modworkshop.net/mod/45444).
	 *
	 *  Each platform has differing support for SMF features.
	 *  - GitHub repositories and ModWorkshop mods support fully automatic updating.
	 *  - GitHub repositories additionally support proper changelogs for mods, so users can see all the differences (across all releases) between their version and the latest. ModWorkshop does not support changelogs.
	 *  - Nexus Mods only allows for telling the user when an update is available, so the other two platforms are preferable.
	 *
	 *  In short: use GitHub if you can, ModWorkshop if you really don't want to, and Nexus Mods as a last resort.
	 */
	url: UrlOrNull
	// Relevant links for the mod.
	links?: Links_Serialize
	conditions?: ManifestConditions_Serialize
	data?: ManifestData_Serialize
	// Settings for the mod that can be customised in the Mod Manager.
	options?: ModOption_Serialize[]
	// Preset combinations of mod options that can be selected all at once.
	presets?: OptionPreset_Serialize[]
}

export type ModInfo = {
	url: string
	version: string
}

export type ModOption = ModOption_Serialize | ModOption_Deserialize

export type ModOptionData = ModOptionData_Serialize | ModOptionData_Deserialize

export type ModOptionData_Deserialize =
	// A boolean option. Can be enabled or disabled by a user.
	| {
			type: "boolean"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met). Preselected options should deliver the "advertised experience". Mods with many standalone options should have the user select their own settings, or provide a conservative default.
			defaultValue: boolean
			// An image representing the option. Should usually be a gameplay image showing the option in use.
			image: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Deserialize
			// Data to conditionally deploy when this option's value is true.
			data?: ManifestData_Deserialize
	  }
	// A selection group, where the user selects only one option to enable from a list of options.
	| {
			type: "selection"
			// The name of the selection group.
			name: UIText
			// A description of the selection group. Can contain multiple sentences.
			description: UIText | null
			// The default-selected option's ID. Will also be used if the selection group itself is disabled (e.g. if it is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Deserialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Deserialize
			// The available options to choose from.
			options: SelectionOption_Deserialize[]
	  }
	// A conditional option. This is a special case; conditional options are not shown to the user, and are instead enabled if and only if the given condition is met.
	| {
			type: "conditional"
			/**
			 *  A condition written in Rune which will enable the option when met.
			 *  Should be formatted as an expression.
			 *  Some helper functions are given in the global scope.
			 *  The framework config and game (version and platform) are available in the global scope as `config` and `game`.
			 *  For example, `mod_enabled("Author.SomeMod@1.0.0") && game.platform == Platform::Steam`.
			 */
			condition: string
			// Data to conditionally deploy when this option's condition evaluates to true.
			data?: ManifestData_Deserialize
	  }
	// A number option. The user can enter a number (optionally with validation).
	| {
			type: "number"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: number
			// Validation settings for this option.
			validation?: NumberOptionValidation_Deserialize
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Deserialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Deserialize
	  }
	// A colour option. The user can select a colour using a visual picker.
	| {
			type: "color"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Whether the colour should include a transparency/alpha value. If disabled (default), the value of this option is of the form "#rrggbb". If enabled, it is "#rrggbbaa".
			alpha?: boolean
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Deserialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Deserialize
	  }
	// A number option. The user can enter a freeform string (optionally with validation).
	| {
			type: "string"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Validation settings for this option.
			validation?: StringOptionValidation_Deserialize
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Deserialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Deserialize
	  }
	// A group of related options, for visual formatting.
	| {
			type: "optionGroup"
			// This entire option group will only be displayed (and only be configurable) if the given condition is met. Should be formatted as an expression; see the documentation for examples.
			displayCondition: string | null
			// The name of the group.
			name: UIText
			// A description of the group. Can contain multiple sentences.
			description: UIText | null
			// A description of the group, to be shown when the display condition is NOT met. Can contain multiple sentences.
			hiddenDescription: UIText | null
			// The options contained within this group.
			options: ModOption_Deserialize[]
			// Preset combinations of mod options that can be selected all at once.
			presets?: OptionPreset_Deserialize[]
			// Data to conditionally deploy when this option group is displayed (when its condition is met).
			data?: ManifestData_Deserialize
	  }

export type ModOptionData_Serialize =
	// A boolean option. Can be enabled or disabled by a user.
	| {
			type: "boolean"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description?: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met). Preselected options should deliver the "advertised experience". Mods with many standalone options should have the user select their own settings, or provide a conservative default.
			defaultValue: boolean
			// An image representing the option. Should usually be a gameplay image showing the option in use.
			image?: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Serialize
			// Data to conditionally deploy when this option's value is true.
			data?: ManifestData_Serialize
	  }
	// A selection group, where the user selects only one option to enable from a list of options.
	| {
			type: "selection"
			// The name of the selection group.
			name: UIText
			// A description of the selection group. Can contain multiple sentences.
			description?: UIText | null
			// The default-selected option's ID. Will also be used if the selection group itself is disabled (e.g. if it is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Serialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Serialize
			// The available options to choose from.
			options: SelectionOption_Serialize[]
	  }
	// A conditional option. This is a special case; conditional options are not shown to the user, and are instead enabled if and only if the given condition is met.
	| {
			type: "conditional"
			/**
			 *  A condition written in Rune which will enable the option when met.
			 *  Should be formatted as an expression.
			 *  Some helper functions are given in the global scope.
			 *  The framework config and game (version and platform) are available in the global scope as `config` and `game`.
			 *  For example, `mod_enabled("Author.SomeMod@1.0.0") && game.platform == Platform::Steam`.
			 */
			condition: string
			// Data to conditionally deploy when this option's condition evaluates to true.
			data?: ManifestData_Serialize
	  }
	// A number option. The user can enter a number (optionally with validation).
	| {
			type: "number"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description?: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: number
			// Validation settings for this option.
			validation: NumberOptionValidation_Serialize
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image?: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Serialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Serialize
	  }
	// A colour option. The user can select a colour using a visual picker.
	| {
			type: "color"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description?: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Whether the colour should include a transparency/alpha value. If disabled (default), the value of this option is of the form "#rrggbb". If enabled, it is "#rrggbbaa".
			alpha: boolean
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image?: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Serialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Serialize
	  }
	// A number option. The user can enter a freeform string (optionally with validation).
	| {
			type: "string"
			// The name of the option.
			name: UIText
			// A description of the option. Can contain multiple sentences.
			description?: UIText | null
			// The default value of this option. Will also be used if the option is disabled (e.g. if this option is part of a group whose `displayCondition` is not met).
			defaultValue: string
			// Validation settings for this option.
			validation: StringOptionValidation_Serialize
			// An image representing the option. Should usually be a gameplay image showing what effect the option might have.
			image?: string | null
			// Conditions which must be met for this option to be configurable.
			conditions?: ManifestConditions_Serialize
			// Data to conditionally deploy when this option is configurable (when all conditions are met).
			data?: ManifestData_Serialize
	  }
	// A group of related options, for visual formatting.
	| {
			type: "optionGroup"
			// This entire option group will only be displayed (and only be configurable) if the given condition is met. Should be formatted as an expression; see the documentation for examples.
			displayCondition?: string | null
			// The name of the group.
			name: UIText
			// A description of the group. Can contain multiple sentences.
			description?: UIText | null
			// A description of the group, to be shown when the display condition is NOT met. Can contain multiple sentences.
			hiddenDescription?: UIText | null
			// The options contained within this group.
			options: ModOption_Serialize[]
			// Preset combinations of mod options that can be selected all at once.
			presets?: OptionPreset_Serialize[]
			// Data to conditionally deploy when this option group is displayed (when its condition is met).
			data?: ManifestData_Serialize
	  }

export type ModOptionValue =
	| { type: "boolean"; value: boolean }
	| { type: "number"; value: number }
	| { type: "selection"; value: string }
	| { type: "color"; value: string }
	| { type: "string"; value: string }

export type ModOption_Deserialize = {
	// An ID for the option. Can be anything, so long as it's not duplicated. This is also used for substitution in content files; `"bla": "#{option:some-id}"` will be replaced with `"bla": true` and `"bla #{option:some-id} bla"` with `"bla true bla"`.
	id: string
} & ModOptionData_Deserialize

export type ModOption_Serialize = {
	// An ID for the option. Can be anything, so long as it's not duplicated. This is also used for substitution in content files; `"bla": "#{option:some-id}"` will be replaced with `"bla": true` and `"bla #{option:some-id} bla"` with `"bla true bla"`.
	id: string
} & ModOptionData_Serialize

// A mod profile.
export type ModProfile = {
	name: string
	deployOrder: string[]
	modOptions: { [key in string]: { [key in string]: ModOptionValue } }
}

export type ModReference = {
	id: string
	version: string
}

export type ModUpgradeProgress = string

export type NumberOptionValidation = NumberOptionValidation_Serialize | NumberOptionValidation_Deserialize

export type NumberOptionValidation_Deserialize = {
	// The minimum value the user is allowed to enter.
	minimum: number | null
	// The minimum value the user is allowed to enter.
	maximum: number | null
	// Whether the user must enter an integer (a whole number).
	integer?: boolean
}

export type NumberOptionValidation_Serialize = {
	// The minimum value the user is allowed to enter.
	minimum?: number | null
	// The minimum value the user is allowed to enter.
	maximum?: number | null
	// Whether the user must enter an integer (a whole number).
	integer?: boolean
}

export type OptionPreset = OptionPreset_Serialize | OptionPreset_Deserialize

export type OptionPreset_Deserialize = {
	// An ID for the preset. Can be anything, so long as it's not duplicated.
	id: string
	// The name of the preset.
	name: UIText
	// A description of the preset. Can contain multiple sentences.
	description: UIText | null
	// An image representing the preset. Should usually be a gameplay image showing the preset in use.
	image: string | null
	// The values of the mod's options for this preset. Options not included will be unchanged.
	values: {
		[key in string]:
			| "Null"
			| ({ Bool: boolean } & { Array?: never; Number?: never; Object?: never; String?: never })
			| ({ Number: ({ f64: number } & { i64?: never; u64?: never }) | ({ i64: number } & { f64?: never; u64?: never }) | ({ u64: number } & { f64?: never; i64?: never }) } & {
					Array?: never
					Bool?: never
					Object?: never
					String?: never
			  })
			| ({ String: string } & { Array?: never; Bool?: never; Number?: never; Object?: never })
			| ({ Array: Value[] } & { Bool?: never; Number?: never; Object?: never; String?: never })
			| ({ Object: { [key in string]: Value } } & { Array?: never; Bool?: never; Number?: never; String?: never })
	}
}

export type OptionPreset_Serialize = {
	// An ID for the preset. Can be anything, so long as it's not duplicated.
	id: string
	// The name of the preset.
	name: UIText
	// A description of the preset. Can contain multiple sentences.
	description?: UIText | null
	// An image representing the preset. Should usually be a gameplay image showing the preset in use.
	image?: string | null
	// The values of the mod's options for this preset. Options not included will be unchanged.
	values: {
		[key in string]:
			| "Null"
			| ({ Bool: boolean } & { Array?: never; Number?: never; Object?: never; String?: never })
			| ({ Number: ({ f64: number } & { i64?: never; u64?: never }) | ({ i64: number } & { f64?: never; u64?: never }) | ({ u64: number } & { f64?: never; i64?: never }) } & {
					Array?: never
					Bool?: never
					Object?: never
					String?: never
			  })
			| ({ String: string } & { Array?: never; Bool?: never; Number?: never; Object?: never })
			| ({ Array: Value[] } & { Bool?: never; Number?: never; Object?: never; String?: never })
			| ({ Object: { [key in string]: Value } } & { Array?: never; Bool?: never; Number?: never; String?: never })
	}
}

export type PackageDefinitionEntity = {
	// The partition to add the path under in the packagedefinition file.
	partition: string
	// The path to add to packagedefinition. Generally, this is a platform-agnostic resource ID.
	path: string
}

export type Platform = "steam" | "epic" | "microsoft" | "gOG"

export type PortedResource = string | { resource: string; forPartition: string }

// The name of a partition in the currently deploying game.
export type RealPartition = string

export type ReferenceType = "install" | "normal" | "weak" | "streamed" | "media" | "state" | "entityType"

// Represents a specific version of a specific game resource, by its RuntimeID and partition.
export type ResourceSpecifier = {
	id: string
	partition: RealPartition
}

export type SelectionOption = SelectionOption_Serialize | SelectionOption_Deserialize

export type SelectionOption_Deserialize = {
	// An ID for the option. Can be anything, so long as it's not duplicated.
	id: string
	// The option's name.
	name: UIText
	// A description of the option. Can contain multiple sentences.
	description: UIText | null
	// An image representing the option. Should usually be a gameplay image showing the option in use.
	image: string | null
	// Conditions which must be met for this option to be selectable.
	conditions?: ManifestConditions_Deserialize
	data?: ManifestData_Deserialize
}

export type SelectionOption_Serialize = {
	// An ID for the option. Can be anything, so long as it's not duplicated.
	id: string
	// The option's name.
	name: UIText
	// A description of the option. Can contain multiple sentences.
	description?: UIText | null
	// An image representing the option. Should usually be a gameplay image showing the option in use.
	image?: string | null
	// Conditions which must be met for this option to be selectable.
	conditions?: ManifestConditions_Serialize
	data?: ManifestData_Serialize
}

export type ServerSideData = {
	unlockables: string | null
	repository: string | null
	contracts: { [key in string]: string }
	worldMapMetadata: { [key in string]: string }
	storyConfig: string | null
	peacockPlugins: string[]
	dynamicResourcesDisabled: boolean
}

export type StorePlatform = "steam" | "epic" | "gog" | "microsoft"

export type StringOptionValidation = StringOptionValidation_Serialize | StringOptionValidation_Deserialize

export type StringOptionValidation_Deserialize = {
	// A regular expression that the user's input must match. Should be a valid Rust regex. For example, `^[a-zA-Z0-9]+$` to require a non-empty string with only alphanumeric characters.
	pattern: string | null
	// The minimum length of the user's input.
	minLength: number | null
	// The maximum length of the user's input.
	maxLength: number | null
}

export type StringOptionValidation_Serialize = {
	// A regular expression that the user's input must match. Should be a valid Rust regex. For example, `^[a-zA-Z0-9]+$` to require a non-empty string with only alphanumeric characters.
	pattern?: string | null
	// The minimum length of the user's input.
	minLength?: number | null
	// The maximum length of the user's input.
	maxLength?: number | null
}

export type TextLines = {
	english: string | null
	french: string | null
	italian: string | null
	german: string | null
	spanish: string | null
	spanish_mexico: string | null
	portuguese_brazil: string | null
	turkish: string | null
	polish: string | null
	russian: string | null
	chinese_simplified: string | null
	chinese_traditional: string | null
	japanese: string | null
	korean: string | null
}

// Some amount of text to be shown in the UI. Can be a single string (assumed to be English), or an object specifying different strings for different languages.
export type UIText = UITextInner

export type UITextInner = string | TextLines

export type UrlOrNull = string | null

export type ValidationResult = { result: "pass" } | { result: "fail"; message: string }

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>

function makeEvent<T>(name: string) {
	const base = {
		listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
		once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
		emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as EventEmit<T>
	}

	const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
		listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
		once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
		emit: ((payload: T) => target.emit(name, payload) as unknown) as EventEmit<T>
	})

	return Object.assign(fn, base)
}
